[workspace]
members = [
    "ecap",
    "erased-ecap",
    "ecap-sys",
    "ecap-cpp",
    "ecap-common",
    "ecap-common-link",
    "sample-adapters/*",
]

[patch.crates-io]
mopa = { path = "mopa" }
