[package]
name = "adapter_minimal"
version = "0.1.0"
authors = ["Mark Simulacrum <mark.simulacrum@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
ecap = { path = "../ecap" }
ecap-common-link = { path = "../ecap-common-link" }
