[package]
name = "ecap-sys"
version = "0.1.0"
authors = ["Mark Simulacrum <mark.simulacrum@gmail.com>"]
links = "ecap"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"
