[package]
name = "adapter-modifying"
version = "0.1.0"
authors = ["Mark Rousskov <mark.simulacrum@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
ecap = { path = "../../ecap" }
ecap-common-link = { path = "../../ecap-common-link" }
